# Длина полей
INGREDIENT_NAME_MAX_LENGTH = 128
MEASUREMENT_UNIT_MAX_LENGTH = 64
RECIPE_NAME_MAX_LENGTH = 256
SHORT_LINK_MAX_LENGTH = 100
SLUG_MAX_LENGTH = 32
TAG_MAX_LENGTH = 32
USERNAME_MAX_LENGTH = 150
USER_FIRST_NAME_MAX_LENGTH = 150
USER_LAST_NAME_MAX_LENGTH = 150

COOKING_TIME_MAX = 32000
COOKING_TIME_MIN = 1

INGREDIENT_AMOUNT_MAX = 32000
INGREDIENT_AMOUNT_MIN = 1

PAGE_SIZE = 6

SHORT_CODE_FOR_LINK = 6
