# Регулярные выражения
USERNAME_REGEX = r'^[\w.@+-]+\Z'

# Пользовательские роли
ROLE_ADMIN = 'admin'
ROLE_AUTHENTICATED_USER = 'auth_user'
VALID_ROLES = [ROLE_AUTHENTICATED_USER, ROLE_ADMIN]

# Длина полей
EMAIL_MAX_LENGTH = 254
INGREDIENT_NAME_MAX_LENGTH = 150
MEASUREMENT_UNIT_MAX_LENGTH = 50
RECIPE_NAME_MAX_LENGTH = 50
ROLE_MAX_LENGTH = 50
SHORT_LINK_MAX_LENGTH = 100
SLUG_MAX_LENGTH = 150
TAG_MAX_LENGTH = 150
USERNAME_MAX_LENGTH = 150
USER_FIRST_NAME_MAX_LENGTH = 150
USER_LAST_NAME_MAX_LENGTH = 150
