server_tokens off;

server {
    listen 80;
    index index.html;
    client_max_body_size 10M;
    
    location /api/docs/ {
        alias /usr/share/nginx/html/api/docs/;
        index redoc.html;
        # try_files $uri $uri/redoc.html;
        try_files $uri $uri/ /api/docs/redoc.html;
    }

    location /api/ {
        client_max_body_size 20M;
        proxy_set_header Host $http_host;
        proxy_pass http://backend:8000/api/;
    }
    
    location /s/ {
        proxy_set_header Host $http_host;
        proxy_pass http://backend:8000/s/;
    }

    location /admin/ {
        client_max_body_size 20M;
        proxy_set_header Host $http_host;
        proxy_pass http://backend:8000/admin/;
    }
    
    # location /static/ {
    #     alias /staticfiles/;
    # }
    location /static/rest_framework/ {
        alias /staticfiles/rest_framework/;
    }
    
    location /static/admin/ {
        alias /staticfiles/admin/;
    }
    
    # Статика фронтенда (JS, CSS) - лежит в /staticfiles/static/
    location /static/js/ {
        alias /staticfiles/static/js/;
    }
    
    location /static/css/ {
        alias /staticfiles/static/css/;
    }
    
    location /static/media/ {
        alias /staticfiles/static/media/;
    }

    location /media/ {
        alias /media/;
    }

    # location / {
    #     alias /staticfiles/;
    #     try_files $uri $uri/ /index.html;
    # }

    # location /recipes {
    #     if ($args ~* "tags=([^&]+)") {
    #         set $tag_args $args;
    #         rewrite ^/recipes$ /api/recipes/?$tag_args last;
    #     }
    #     try_files $uri /index.html;
    # }

    location / {
        root /staticfiles/;
        try_files $uri /index.html;
        index index.htm;
    }
}
