# Generated by Django 6.0.3 on 2026-03-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
